### ISSUE TITLE
Can share the script to generate SQuAD format files？

### ISSUE THREAD

**Issue by shaoqb** [mineshmathew/DocVQA#2]

**Comment by shaoqb** [comment]
By the way, what is the performance of M4C on the docvqa dataset？

**Comment by mineshmathew** [comment]
@shaoqb M4C results are reported in this paper - https://arxiv.org/abs/2007.00398

**Comment by mineshmathew** [comment]
the way we generated SQuAD style data is explained in detail in the README
Morever the SQuAD style data is also provided
