### ISSUE TITLE
Unable to access DOCVQA.org to access DOCVQA website.

### ISSUE THREAD

**Issue by PVSS** [mineshmathew/DocVQA#3]
https://docvqa.org isnt accessible to download the data.

**Comment by mineshmathew** [comment]
Following a cyber attack,  many servers including docvqa server were shutdown. It will take a few more days  before the technical team at the university fix it.

Updates are posted here https://uab.cat/en/

**Comment by mineshmathew** [comment]
The docvqa.org is still not live following the cyber attack on servers of UAB,
Those who like to download docvqa and infographicvqa datasets can download it from RRC portal

https://rrc.cvc.uab.es/?ch=17

**Comment by mineshmathew** [comment]
docvqa.org is back online.
Closing this
